#!/bin/sh

LAUNCH_NS = "python -Wignore -m Pyro4.naming"
eval ${LAUNCH_NS} &

echo "Starting eyetracker"
ENGINE = "coxlab_eyetracker_engine"
eval ${ENGINE} &

GUI = "coxlab_eyetracker_gui"
eval ${GUI}

NS_PID=`ps ax | grep -e "${LAUNCH_NS}" | grep -v grep | awk '{print $1}'`
ENGINE_PID=`ps ax | grep -e "${ENGINE}" | grep -v grep | awk '{print $1}'`

kill $NS_PID
kill $ENGINE_PID