#!/usr/bin/env python

from coxlab_eyetracker import *
        
if __name__ == "__main__":
    
    et = EyeTrackerController()
    gui = EyeTrackerGUI(et)
    
    print "ready"
    gui.mainloop()
    