#!/usr/bin/env python
# -*- coding: utf-8 -*-

from coxlab_eyetracker.controller import EyeTrackerController
from coxlab_eyetracker.gui import EyeTrackerGUI

if __name__ == '__main__':

    et = EyeTrackerController()
    gui = EyeTrackerGUI(et)

    print 'ready'
    gui.mainloop()
